export enum FirefighterRank {
    SECOND_CLASS = 'SECOND_CLASS',
    FIRST_CLASS = 'FIRST_CLASS',
    CORPORAL = 'CORPORAL',
    CHIEF_CORPORAL = 'CHIEF_CORPORAL',
    SERGEANT = 'SERGEANT',
    CHIEF_SERGEANT = 'CHIEF_SERGEANT',
    ADJUTANT = 'ADJUTANT',
    CHIEF_ADJUTANT = 'CHIEF_ADJUTANT',
    LIEUTENANT = 'LIEUTENANT',
}
